services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - kpro_data:/var/lib/keycard_shell/data/
      - static_volume:/home/keycard_shell/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:17.4-alpine
    volumes:
      - /docker/shell/db/data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 3000:3000
    depends_on:
      - web
    volumes:
      - static_volume:
      - kpro_data:
