services:
  web:
    build: .
    container_name: keycard_shell
    volumes:
      - kshell_data:/var/lib/keycard_shell/data/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17.4-alpine
    container_name: keycard_shell_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - 5432:5432

volumes:
  postgres_data_dev:
  kshell_data: