services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - kshell_data:/var/lib/keycard_shell/data/
      - static_volume:/home/keycard_shell/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:17.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
      - 3000:443
    depends_on:
      - web
    volumes:
      - static_volume:/home/keycard_shell/web/staticfiles
      - kshell_data:/var/lib/keycard_shell/data/

volumes:
  postgres_data:
  kshell_data:
  static_volume: