services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        UID: ${UID:-100000}
        GID: ${GID:-999}
    volumes:
      - /docker/shell/upload:/var/lib/keycard_shell/data/
      - /docker/shell/app:/home/keycard_shell/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:17.4-alpine
    volumes:
      - /docker/shell/db/data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 3000:80
    depends_on:
      - web
    volumes:
      - /docker/shell/app:/home/keycard_shell/web/staticfiles
      - /docker/shell/upload:/var/lib/keycard_shell/data/
